name: Compress Images

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compress images with Calibre
        uses: calibreapp/image-actions@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: 80
          pngQuality: 80

      - name: Commit optimized images
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add images/
          git commit -m "Auto-compressed images" || echo "No changes to commit"
          git push
